PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sim: <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX fam: <http://www.ifi.uio.no/IN3060/family#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  sim:Homer foaf:knows ?relative .
}
WHERE {
  {
    sim:Homer fam:isRelativeOf ?relative .    # Homer is related to someone
  }
  UNION                                       # "or"
  {
    ?relative fam:isRelativeOf sim:Homer .    # Someone is related to Homer
  }

  ?relative rdf:type foaf:Person .            # that someone is a person
}
