PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sim: <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX fam: <http://www.ifi.uio.no/IN3060/family#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?person ?name WHERE {
    ?person rdf:type foaf:Person . 			# selects all resources that is a "Person"
  	OPTIONAL { ?person foaf:name ?name .  }	# also selects name from each person if it exists
}
ORDER BY ?person